/*************************************************
 * Module:      Ultrasonic Sensor
 * File Name:   Ultrasonic.h
 * Description: Header File for Ultrasonic Sensor
 * Author:      Ziad Hesham Ghonim
 *************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "My_Standard_types.h"

/*******************************************************************************
                             Definitions
 *******************************************************************************/
#define Ultrasonic_Trigger_Port   PORTB_ID
#define Ultrasonic_Trigger_pin    PIN5_ID

/*******************************************************************************
                             Functions Prototypes
 *******************************************************************************/

/*******************************************************************************
 Description : Initialize the Ultrasonic Sensor:
               1- initialize ICU driver.
               2- Setup the ICU call back function.
               3- setup the direction for the trigger pin.
 *******************************************************************************/
void Ultrasonic_init(void);

/*******************************************************************************
 Description : Send the Trigger pulse to the ultrasonic.
 *******************************************************************************/
void Ultrasonic_Trigger(void);

/*******************************************************************************
 Description : 1- Send the trigger pulse by using Ultrasonic_Trigger function.
               2- Start the measurements by the ICU from this moment.
 *******************************************************************************/
uint16 Ultrasonic_readDistance(void);

/******************************************************************************************************
 Description : This is the Call Back Function called by the ICU Driver
               It is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 ******************************************************************************************************/
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
